db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  environment:
    RAILS_ENV: production
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
# docker-compose run web rake db:create db:schema:load db:seed