test: &default

  # Credentials for REST APIs
  client_id: <%= ENV["PAYPAL_REST_ID"] %>
  client_secret: <%= ENV["PAYPAL_REST_SECRET"] %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-X
  username: <%= ENV["PAYPAL_CLASSIC_SANDBOX_USERNAME"] %>
  password: <%= ENV["PAYPAL_CLASSIC_SANDBOX_PASSWORD"] %>
  signature: <%= ENV["PAYPAL_CLASSIC_SANDBOX_SIGN"] %>
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: <%= ENV["PAYPAL_SANDBOX_EMAIL"] %>

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
#  mode: live
#  app_id: <%= ENV["PAYPAL_CLASSIC_APP_ID"] %>
#  username: <%= ENV["PAYPAL_CLASSIC_LIVE_USERNAME"] %>
#  password: <%= ENV["PAYPAL_CLASSIC_LIVE_PASSWORD"] %>
#  signature: <%= ENV["PAYPAL_CLASSIC_LIVE_SIGN"] %>
